tests:
### rtimer test
  - name: timer-rtimer
    timeout: 120
    devices:
      - name: receiver
        programdir: examples/inga_tests/timer-tests
        program: rtimer-test
        instrument: []
        debug: []
        cflags: "-fno-inline"
        graph_options: ""
