tests:
### rtimer test
  - name: timer-rtimer
    timeout: 1200
    devices:
      - name: node
        programdir: examples/inga_tests/timer-tests
        program: rtimer-test
        instrument: []
        debug: []
        cflags: "-fno-inline"
        graph_options: ""
