# Test suite
suite:
    logbase:   ../../log/
    logpattern: date-tag
    contikibase: ../../
    contikiscm: git # Here only git and none are supported at the moment
    testdirs:
        - sensor-tests
        - net-tests-rime
        - net-tests-ip
        - foodir
    testcases:
        - sensor-acc
        - sensor-gyro
        - sensor-battery
        - timer-rtimer
        - fat-default
        - fat-coop

