tests:
### RIME stack test
  - name: net-rime
    timeout: 120
    devices:
      - name: sender
        programdir: examples/inga_tests/net-tests
        program: rime-sender
        instrument: []
        debug: []
        cflags: "-fno-inline"
        graph_options: ""
    devices:
      - name: receiver
        programdir: examples/inga_tests/net-tests
        program: rime-receiver
        instrument: []
        debug: []
        cflags: "-fno-inline"
        graph_options: ""

  - name: net-udp
    timeout: 120
    devices:
      - name: sender
        programdir: examples/inga_tests/net-tests
        program: udp-sender
        instrument: []
        debug: []
        cflags: "-fno-inline"
        graph_options: ""
    devices:
      - name: receiver
        programdir: examples/inga_tests/net-tests
        program: udp-receiver
        instrument: []
        debug: []
        cflags: "-fno-inline"
        graph_options: ""
